package pojos;
// Generated May 16, 2016 10:12:23 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lectures generated by hbm2java
 */
public class Lectures  implements java.io.Serializable {


     private Integer lectureId;
     private String name;
     private int year;
     private Set documents = new HashSet(0);

    public Lectures() {
    }

	
    public Lectures(String name, int year) {
        this.name = name;
        this.year = year;
    }
    public Lectures(String name, int year, Set documents) {
       this.name = name;
       this.year = year;
       this.documents = documents;
    }
   
    public Integer getLectureId() {
        return this.lectureId;
    }
    
    public void setLectureId(Integer lectureId) {
        this.lectureId = lectureId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public Set getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set documents) {
        this.documents = documents;
    }




}


