package pojos;
// Generated May 25, 2016 12:15:23 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private Integer idlog;
     private Users users;
     private Integer activity;
     private Date lastDate;

    public Log() {
    }

    public Log(Users users, Integer activity, Date lastDate) {
       this.users = users;
       this.activity = activity;
       this.lastDate = lastDate;
    }
   
    public Integer getIdlog() {
        return this.idlog;
    }
    
    public void setIdlog(Integer idlog) {
        this.idlog = idlog;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Integer getActivity() {
        return this.activity;
    }
    
    public void setActivity(Integer activity) {
        this.activity = activity;
    }
    public Date getLastDate() {
        return this.lastDate;
    }
    
    public void setLastDate(Date lastDate) {
        this.lastDate = lastDate;
    }




}


