package pojos;
// Generated May 16, 2016 10:12:23 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Notes generated by hbm2java
 */
public class Notes  implements java.io.Serializable {


     private Integer noteId;
     private int userId;
     private int lectureId;
     private String title;
     private Date postDate;
     private Integer resourceId;
     private String text;
     private String code;

    public Notes() {
    }

	
    public Notes(int userId, int lectureId, String title, Date postDate) {
        this.userId = userId;
        this.lectureId = lectureId;
        this.title = title;
        this.postDate = postDate;
    }
    public Notes(int userId, int lectureId, String title, Date postDate, Integer resourceId, String text, String code) {
       this.userId = userId;
       this.lectureId = lectureId;
       this.title = title;
       this.postDate = postDate;
       this.resourceId = resourceId;
       this.text = text;
       this.code = code;
    }
   
    public Integer getNoteId() {
        return this.noteId;
    }
    
    public void setNoteId(Integer noteId) {
        this.noteId = noteId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getLectureId() {
        return this.lectureId;
    }
    
    public void setLectureId(int lectureId) {
        this.lectureId = lectureId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }
    public Integer getResourceId() {
        return this.resourceId;
    }
    
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }




}


