package pojos;
// Generated May 16, 2016 10:12:23 AM by Hibernate Tools 4.3.1



/**
 * Resources generated by hbm2java
 */
public class Resources  implements java.io.Serializable {


     private Integer resourceId;
     private String url;

    public Resources() {
    }

    public Resources(String url) {
       this.url = url;
    }
   
    public Integer getResourceId() {
        return this.resourceId;
    }
    
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


