package pojos;
// Generated May 16, 2016 10:12:23 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String authority;
     private String password;
     private String name;
     private String surname;
     private String EMail;
     private Integer resourceId;
     private Date registerDate;
     private Set documents = new HashSet(0);

    public Users() {
    }

	
    public Users(String authority, String password, String name, String surname, String EMail, Date registerDate) {
        this.authority = authority;
        this.password = password;
        this.name = name;
        this.surname = surname;
        this.EMail = EMail;
        this.registerDate = registerDate;
    }
    public Users(String authority, String password, String name, String surname, String EMail, Integer resourceId, Date registerDate, Set documents) {
       this.authority = authority;
       this.password = password;
       this.name = name;
       this.surname = surname;
       this.EMail = EMail;
       this.resourceId = resourceId;
       this.registerDate = registerDate;
       this.documents = documents;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public Integer getResourceId() {
        return this.resourceId;
    }
    
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }
    public Date getRegisterDate() {
        return this.registerDate;
    }
    
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }
    public Set getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set documents) {
        this.documents = documents;
    }




}


